{
    "swagger": "2.0",
    "info": {
        "title": "Media Stream Recording Profile",
        "version": "2.0.0",
        "description": "スマートデバイスによる写真撮影、動画録画または音声録音などの操作を行うAPI。"
    },
    "consumes": [
        "application/x-www-form-urlencoded",
        "multipart/form-data"
    ],
    "paths": {
        "/mediaRecorder": {
            "get": {
                "x-type": "one-shot",
                "summary": "",
                "description": "",
                "parameters": [
                    {
                        "name": "serviceId",
                        "in": "query",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/MediaRecorderResponse"
						},
                        "examples": {
                            "application/json": {
                                "result": 0,
                                "product": "Example System",
                                "version": "1.0.0",
								"recorders": [
									{
										"id": "photo_0",
										"name": "Dummy Camera Recorder - back",
										"state": "inactive",
										"imageWidth": 3264,
										"imageHeight": 2448,
										"previewWidth": 640,
										"previewHeight": 480,
										"previewMaxFrameRate": 10,
										"mimeType": "image/png",
										"config": ""
									},
									{
										"id": "photo_1",
										"name": "Dummy Camera Recorder - front",
										"state": "inactive",
										"imageWidth": 1280,
										"imageHeight": 960,
										"previewWidth": 640,
										"previewHeight": 480,
										"previewMaxFrameRate": 10,
										"mimeType": "image/png",
										"config": ""
									},
									{
										"id": "video_0",
										"name": "Dummy Video Recorder - back",
										"state": "inactive",
										"imageWidth": 640,
										"imageHeight": 480,
										"mimeType": "video/3gp",
										"config": ""
									},
									{
										"id": "video_1",
										"name": "Dummy Video Recorder - front",
										"state": "inactive",
										"imageWidth": 640,
										"imageHeight": 480,
										"mimeType": "video/3gp",
										"config": ""
									},
									{
										"id": "audio",
										"name": "Dummy Audio Recorder",
										"state": "inactive",
										"mimeType": "audio/3gp",
										"config": ""
									},
									{
										"id": "screen",
										"name": "Dummy Screen",
										"state": "inactive",
										"imageWidth": 1080,
										"imageHeight": 1776,
										"previewWidth": 270,
										"previewHeight": 444,
										"previewMaxFrameRate": 10,
										"mimeType": "video/x-mjpeg",
										"config": ""
									}
								]
                            }
                        }
                    }
                }
            }
        },
        "/takePhoto": {
            "post": {
                "x-type": "one-shot",
                "summary": "",
                "description": "",
                "parameters": [
                    {
                        "name": "serviceId",
                        "in": "formData",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "name": "target",
                        "in": "formData",
                        "required": false,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/TakePhotoResponse"
						},
                        "examples": {
                            "application/json": {
                                "result": 0,
                                "product": "Example System",
                                "version": "1.0.0",
								"uri": "Dummy URI",
								"path": "Dummy Path"
                            }
                        }
                    }
                }
            }
        },
        "/record": {
            "post": {
                "x-type": "one-shot",
                "summary": "",
                "description": "",
                "parameters": [
                    {
                        "name": "serviceId",
                        "in": "formData",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "name": "target",
                        "in": "formData",
                        "required": false,
                        "type": "string"
                    },
                    {
                        "name": "timeslice",
                        "in": "formData",
                        "required": false,
                        "minimum": 0.0,
                        "type": "integer",
                        "format": "int64"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/RecordResponse"
						},
                        "examples": {
                            "application/json": {
                                "result": 0,
                                "product": "Example System",
                                "version": "1.0.0",
								"uri": "Dummy URI",
								"path": "Dummy Path"
                            }
                        }
                    }
                }
            }
        },
        "/pause": {
            "put": {
                "x-type": "one-shot",
                "summary": "",
                "description": "",
                "parameters": [
                    {
                        "name": "serviceId",
                        "in": "formData",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "name": "target",
                        "in": "formData",
                        "required": false,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/RecorderControlResponse"
                        },
                        "examples": {
                            "application/json": {
                                "result": 0,
                                "product": "Example System",
                                "version": "1.0.0"
                            }
                        }
                    }
                }
            }
        },
        "/resume": {
            "put": {
                "x-type": "one-shot",
                "summary": "",
                "description": "",
                "parameters": [
                    {
                        "name": "serviceId",
                        "in": "formData",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "name": "target",
                        "in": "formData",
                        "required": false,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/RecorderControlResponse"
                        },
                        "examples": {
                            "application/json": {
                                "result": 0,
                                "product": "Example System",
                                "version": "1.0.0"
                            }
                        }
                    }
                }
            }
        },
        "/stop": {
            "put": {
                "x-type": "one-shot",
                "summary": "",
                "description": "",
                "parameters": [
                    {
                        "name": "serviceId",
                        "in": "formData",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "name": "target",
                        "in": "formData",
                        "required": false,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/RecorderControlResponse"
                        },
                        "examples": {
                            "application/json": {
                                "result": 0,
                                "product": "Example System",
                                "version": "1.0.0"
                            }
                        }
                    }
                }
            }
        },
        "/muteTrack": {
            "put": {
                "x-type": "one-shot",
                "summary": "",
                "description": "",
                "parameters": [
                    {
                        "name": "serviceId",
                        "in": "formData",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "name": "target",
                        "in": "formData",
                        "required": false,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/RecorderControlResponse"
                        },
                        "examples": {
                            "application/json": {
                                "result": 0,
                                "product": "Example System",
                                "version": "1.0.0"
                            }
                        }
                    }
                }
            }
        },
        "/unmuteTrack": {
            "put": {
                "x-type": "one-shot",
                "summary": "",
                "description": "",
                "parameters": [
                    {
                        "name": "serviceId",
                        "in": "formData",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "name": "target",
                        "in": "formData",
                        "required": false,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/RecorderControlResponse"
                        },
                        "examples": {
                            "application/json": {
                                "result": 0,
                                "product": "Example System",
                                "version": "1.0.0"
                            }
                        }
                    }
                }
            }
        },
        "/options": {
            "get": {
                "x-type": "one-shot",
                "summary": "",
                "description": "",
                "parameters": [
                    {
                        "name": "serviceId",
                        "in": "query",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "name": "target",
                        "in": "query",
                        "required": false,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/OptionsResponse"
						},
                        "examples": {
                            "application/json": {
                                "result": 0,
                                "product": "Example System",
                                "version": "1.0.0",
								"imageSize": [
									{
										"width": 3264,
										"height": 2448
									},
									{
										"width": 3200,
										"height": 2400
									},
									{
										"width": 2592,
										"height": 1944
									},
									{
										"width": 2048,
										"height": 1536
									},
									{
										"width": 1920,
										"height": 1080
									},
									{
										"width": 1600,
										"height": 1200
									},
									{
										"width": 1280,
										"height": 960
									},
									{
										"width": 1280,
										"height": 768
									},
									{
										"width": 1280,
										"height": 720
									},
									{
										"width": 1024,
										"height": 768
									},
									{
										"width": 800,
										"height": 600
									},
									{
										"width": 800,
										"height": 480
									},
									{
										"width": 720,
										"height": 480
									},
									{
										"width": 640,
										"height": 480
									},
									{
										"width": 352,
										"height": 288
									},
									{
										"width": 320,
										"height": 240
									},
									{
										"width": 176,
										"height": 144
									}
								],
								"previewSize": [
									{
										"width": 1920,
										"height": 1080
									},
									{
										"width": 1600,
										"height": 1200
									},
									{
										"width": 1280,
										"height": 960
									},
									{
										"width": 1280,
										"height": 768
									},
									{
										"width": 1280,
										"height": 720
									},
									{
										"width": 1024,
										"height": 768
									},
									{
										"width": 800,
										"height": 600
									},
									{
										"width": 800,
										"height": 480
									},
									{
										"width": 720,
										"height": 480
									},
									{
										"width": 640,
										"height": 480
									},
									{
										"width": 352,
										"height": 288
									},
									{
										"width": 320,
										"height": 240
									},
									{
										"width": 176,
										"height": 144
									}
								],
								"mimeType": [
									"image/png"
								]
                            }
                        }
                    }
                }
            },
            "put": {
                "x-type": "one-shot",
                "summary": "",
                "description": "",
                "parameters": [
                    {
                        "name": "serviceId",
                        "in": "formData",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "name": "target",
                        "in": "formData",
                        "required": false,
                        "type": "string"
                    },
                    {
                        "name": "imageWidth",
                        "in": "formData",
                        "required": false,
                        "type": "integer"
                    },
                    {
                        "name": "imageHeight",
                        "in": "formData",
                        "required": false,
                        "type": "integer"
                    },
                    {
                        "name": "previewWidth",
                        "in": "formData",
                        "required": false,
                        "type": "integer"
                    },
                    {
                        "name": "previewHeight",
                        "in": "formData",
                        "required": false,
                        "type": "integer"
                    },
                    {
                        "name": "previewMaxFrameRate",
                        "in": "formData",
                        "required": false,
                        "type": "number",
                        "minimum": 0.0,
                        "exclusiveMinimum": true
                    },
                    {
                        "name": "mimeType",
                        "in": "formData",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/RecorderControlResponse"
                        },
                        "examples": {
                            "application/json": {
                                "result": 0,
                                "product": "Example System",
                                "version": "1.0.0"
                            }
                        }
                    }
                }
            }
        },
        "/onPhoto": {
            "get": {
                "x-type": "one-shot",
                "summary": "",
                "description": "",
                "parameters": [
                    {
                        "name": "serviceId",
                        "in": "query",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/PhotoResponse"
                        },
                        "examples": {
                            "application/json": {
                                "result": 0,
                                "product": "Example System",
                                "version": "1.0.0",
								"uri": "Dummy URI",
								"path": "Dummy Path"
                            }
                        }
                    }
                }
            },
            "put": {
                "x-type": "event",
                "summary": "",
                "description": "",
                "parameters": [
                    {
                        "name": "serviceId",
                        "in": "formData",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "name": "interval",
                        "in": "formData",
                        "required": false,
                        "type": "integer",
                        "format": "int64"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/EventRegistrationResponse"
                        },
                        "examples": {
                            "application/json": {
                                "result": 0,
                                "product": "Example System",
                                "version": "1.0.0"
                            }
                        }
                    }
                },
                "x-event": {
                    "schema": {
                        "$ref": "#/definitions/PhotoEvent"
                    }
                }
            },
            "delete": {
                "x-type": "event",
                "summary": "",
                "description": "",
                "parameters": [
                    {
                        "name": "serviceId",
                        "in": "query",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/EventUnregistrationResponse"
                        },
                        "examples": {
                            "application/json": {
                                "result": 0,
                                "product": "Example System",
                                "version": "1.0.0"
                            }
                        }
                    }
                }
            }
        },
        "/preview": {
            "get": {
                "x-type": "one-shot",
                "summary": "",
                "description": "",
                "parameters": [
                    {
                        "name": "serviceId",
                        "in": "query",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "name": "target",
                        "in": "query",
                        "required": false,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            },
            "put": {
                "x-type": "streaming",
                "summary": "",
                "description": "",
                "parameters": [
                    {
                        "name": "serviceId",
                        "in": "formData",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "name": "target",
                        "in": "formData",
                        "required": false,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/PreviewStartResponse"
						},
                        "examples": {
                            "application/json": {
                                "result": 0,
                                "product": "Example System",
                                "version": "1.0.0",
								"uri": "Dummy Preview URI"
                            }
                        }
                    }
                }
            },
            "delete": {
                "x-type": "streaming",
                "summary": "",
                "description": "",
                "parameters": [
                    {
                        "name": "serviceId",
                        "in": "query",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "name": "target",
                        "in": "query",
                        "required": false,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/PreviewStopResponse"
                        },
                        "examples": {
                            "application/json": {
                                "result": 0,
                                "product": "Example System",
                                "version": "1.0.0"
                            }
                        }
                    }
                }
            }
        },
        "/onRecordingChange": {
            "get": {
                "x-type": "one-shot",
                "summary": "",
                "description": "",
                "parameters": [
                    {
                        "name": "serviceId",
                        "in": "query",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/RecordingStatusResponse"
						},
                        "examples": {
                            "application/json": {
                                "result": 0,
                                "product": "Example System",
                                "version": "1.0.0",
								"media": {
									"status": "stop",
									"path": "Dummy Path",
									"mimeType": "video/3gp"
								}
                            }
                        }
                    }
                }
            },
            "put": {
                "x-type": "event",
                "summary": "",
                "description": "",
                "parameters": [
                    {
                        "name": "serviceId",
                        "in": "formData",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "name": "interval",
                        "in": "formData",
                        "required": false,
                        "type": "integer",
                        "format": "int64"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/EventRegistrationResponse"
                        },
                        "examples": {
                            "application/json": {
                                "result": 0,
                                "product": "Example System",
                                "version": "1.0.0"
                            }
                        }
                    }
                },
                "x-event": {
                    "schema": {
                        "$ref": "#/definitions/RecordingStatusEvent"
                    }
                }
            },
            "delete": {
                "x-type": "event",
                "summary": "",
                "description": "",
                "parameters": [
                    {
                        "name": "serviceId",
                        "in": "query",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/EventUnregistrationResponse"
                        },
                        "examples": {
                            "application/json": {
                                "result": 0,
                                "product": "Example System",
                                "version": "1.0.0"
                            }
                        }
                    }
                }
            }
        }
    },

    "definitions": {
        "MediaRecorderResponse": {
            "type": "object",
            "allOf": [
                {
                    "$ref": "#/definitions/CommonResponse"
                },
                {
                    "type": "object",
                    "required": [
                        "recorders"
                    ],
                    "properties": {
                        "recorders": {
                            "type": "array",
                            "title": "レコーダーリスト",
                            "description": "レコーダー情報の配列。",
                            "items": {
                                "type": "object",
                                "required": [
                                    "id",
                                    "name",
                                    "state",
                                    "mimeType",
                                    "config"
                                ],
                                "properties": {
                                    "id": {
                                        "type": "string",
                                        "title": "レコーダーID",
                                        "description": "レコーダーを識別するID。"
                                    },
                                    "name": {
                                        "type": "string",
                                        "title": "レコーダー名",
                                        "description": "レコーダー名。"
                                    },
                                    "state": {
                                        "type": "string",
                                        "title": "レコーダーの状態",
                                        "description": "レコーダーの状態。",
                                        "enum": [
                                            "inactive", "recording", "paused"
                                        ]
                                    },
                                    "mimeType": {
                                        "type": "string",
                                        "title": "MIME Type",
                                        "description": "レコーダーのエンコードするタイプ。"
                                    },
                                    "config": {
                                        "type": "string",
                                        "title": "コンフィグ",
                                        "description": "カメラに設定がある場合には、ここに文字列としてデータが格納されている。"
                                    },
                                    "imageWidth": {
                                        "type": "integer",
                                        "title": "画像の横幅",
                                        "description": "レコーダーの現在の横幅。単位はピクセル。録音の場合は省略可。"
                                    },
                                    "imageHeight": {
                                        "type": "integer",
                                        "title": "画像の縦幅",
                                        "description": "レコーダーの現在の縦幅。単位はピクセル。録音の場合は省略可。"
                                    },
                                    "previewWidth": {
                                        "type": "integer",
                                        "title": "プレビューの横幅",
                                        "description": "プレビューの現在の横幅。単位はピクセル。録音の場合は省略可。"
                                    },
                                    "previewHeight": {
                                        "type": "integer",
                                        "title": "プレビューの縦幅",
                                        "description": "プレビューの現在の縦幅。単位はピクセル。録音の場合は省略可。"
                                    },
                                    "previewMaxFrameRate": {
                                        "type": "number",
                                        "title": "プレビューの最大フレームレート",
                                        "description": "現在のプレビューのフレームレートの最大値。単位はfps。録音の場合は省略可。"
                                    },
                                    "audio": {
                                        "type": "object",
                                        "title": "音声情報",
                                        "description": "録音する音声に関する情報。",
                                        "required": [
                                            "channels",
                                            "sampleRate",
                                            "sampleSize",
                                            "blockSize"
                                        ],
                                        "properties": {
                                            "channels": {
                                                "type": "integer",
                                                "title": "チャンネル数",
                                                "description": "音声のチャンネル数。"
                                            },
                                            "sampleRate": {
                                                "type": "number",
                                                "title": "サンプルレート",
                                                "description": "音声のサンプルレート。単位はHz。"
                                            },
                                            "sampleSize": {
                                                "type": "integer",
                                                "title": "サンプルサイズ",
                                                "description": "音声のサンプルサイズ。単位はビット。"
                                            },
                                            "blockSize": {
                                                "type": "integer",
                                                "title": "ブロックサイズ",
                                                "description": "音声のブロックサイズ。単位はバイト。"
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            ]
        },
        "TakePhotoResponse": {
            "type": "object",
            "allOf": [
                {
                    "$ref": "#/definitions/CommonResponse"
                },
                {
                    "type": "object",
                    "required": [
                        "uri",
                        "path"
                    ],
                    "properties": {
                        "uri": {
                            "type": "string",
                            "title": "URI",
                            "description": "撮影された写真のURI。"
                        },
                        "path": {
                            "type": "string",
                            "title": "ファイルパス",
                            "description": "撮影された写真へのファイルパス。ルートはデバイスプラグインごとに異なる。File APIのパラメータとして使用可能。"
                        }
                    }
                }
            ]
        },
        "RecordResponse": {
            "type": "object",
            "allOf": [
                {
                    "$ref": "#/definitions/CommonResponse"
                },
                {
                    "type": "object",
                    "required": [
                        "uri",
                        "path"
                    ],
                    "properties": {
                        "uri": {
                            "type": "string",
                            "title": "URI",
                            "description": "動画または音声のURI。"
                        },
                        "path": {
                            "type": "string",
                            "title": "ファイルパス",
                            "description": "動画または音声へのファイルパス。ルートはデバイスプラグインごとに異なる。File APIのパラメータとして使用可能。"
                        }
                    }
                }
            ]
        },
        "OptionsResponse": {
            "type": "object",
            "allOf": [
                {
                    "$ref": "#/definitions/CommonResponse"
                },
                {
                    "required": [
                        "mimeType"
                    ],
                    "properties": {
                        "mimeType": {
                            "type": "array",
                            "title": "MIME Type",
                            "description": "録画・録音する際のエンコードするタイプの一覧",
                            "items": {
                                "type": "string"
                            }
                        },
                        "imageSizes": {
                            "type": "array",
                            "title": "撮影時の解像度の一覧",
                            "description": "レコーダーのサポートする画像の解像度の一覧。録音の場合は省略可。プラグイン側でリサイズすることでサポートするサイズも含めてよい。",
                            "items": {
                                "type": "object",
                                "title": "解像度",
                                "description": "画像の解像度。",
                                "required": [
                                    "width",
                                    "height"
                                ],
                                "properties": {
                                    "width": {
                                        "type": "integer",
                                        "title": "横幅",
                                        "description": "画像の横幅。単位はピクセル。"
                                    },
                                    "height": {
                                        "type": "integer",
                                        "title": "縦幅",
                                        "description": "画像の縦幅。単位はピクセル。"
                                    }
                                }
                            }
                        },
                        "previewSizes": {
                            "type": "array",
                            "title": "プレビュー時の解像度の一覧",
                            "description": "プレビューで利用可能な解像度の一覧。録音の場合、またはプレビューを 提供しない場合は省略可。プラグイン側でリサイズすることでサポートするサイズも含めてよい。",
                            "items": {
                                "type": "object",
                                "title": "解像度",
                                "description": "画像の解像度。",
                                "required": [
                                    "width",
                                    "height"
                                ],
                                "properties": {
                                    "width": {
                                        "type": "integer",
                                        "title": "横幅",
                                        "description": "画像の横幅。単位はピクセル。"
                                    },
                                    "height": {
                                        "type": "integer",
                                        "title": "縦幅",
                                        "description": "画像の縦幅。単位はピクセル。"
                                    }
                                }
                            }
                        }
                    }
                }
            ]
        },
        "PhotoResponse": {
            "type": "object",
            "allOf": [
                {
                    "$ref": "#/definitions/CommonResponse"
                },
                {
                    "$ref": "#/definitions/PhotoInfo"
                }
            ]
        },
        "PhotoEvent": {
            "type": "object",
            "allOf": [
                {
                    "$ref": "#/definitions/CommonEvent"
                },
                {
                    "$ref": "#/definitions/PhotoInfo"
                }
            ]
        },
        "PhotoInfo": {
            "type": "object",
            "required": [
                "photo"
            ],
            "properties": {
                "photo": {
                    "type": "object",
                    "title": "写真データ",
                    "description": "撮影された写真データ。",
                    "required": [
                        "path",
                        "mimeType"
                    ],
                    "properties": {
                        "path": {
                            "type": "string",
                            "title": "ファイルパス",
                            "description": "ファイルが存在するパス。ルートはデバイスプラグインごとに異なる。File APIで使用可能。"
                        },
                        "mimeType": {
                            "type": "string",
                            "title": "MIME Type",
                            "description": "撮影された写真のMIME Type。動画・音声を識別するために使用する。"
                        }
                    }
                }
            }
        },
        "PreviewStartResponse": {
            "type": "object",
            "allOf": [
                {
                    "$ref": "#/definitions/CommonResponse"
                },
                {
                    "type": "object",
                    "required": [
                        "uri"
                    ],
                    "properties": {
                        "uri": {
                            "type": "string",
                            "title": "プレビュー配信URI",
                            "description": "開始したプレビューの配信用URI。形式はMotionJPEGとする。"
                        },
                        "audio": {
                            "type": "object",
                            "title": "音声配信情報",
                            "description": "音声配信に関する情報。音声のみの配信をサポートしない場合は省略可。",
                            "required": [
                                "uri"
                            ],
                            "properties": {
                                "uri": {
                                    "type": "string",
                                    "title": "音声配信URI",
                                    "description": "音声配信URI。"
                                }
                            }
                        }
                    }
                }
            ]
        },
        "PreviewStopResponse": {
            "type": "object",
            "allOf": [
                {
                    "$ref": "#/definitions/CommonResponse"
                }
            ]
        },
        "RecordingStatusResponse": {
            "type": "object",
            "allOf": [
                {
                    "$ref": "#/definitions/CommonResponse"
                },
                {
                    "$ref": "#/definitions/RecordingStatusInfo"
                }
            ]
        },
        "RecordingStatusEvent": {
            "type": "object",
            "allOf": [
                {
                    "$ref": "#/definitions/CommonEvent"
                },
                {
                    "$ref": "#/definitions/RecordingStatusInfo"
                }
            ]
        },
        "RecordingStatusInfo": {
            "type": "object",
            "required": [
                "media"
            ],
            "properties": {
                "media": {
                    "type": "object",
                    "title": "レコーディング情報",
                    "description": "レコーディング情報",
                    "required": [
                        "status",
                        "path",
                        "mimeType"
                    ],
                    "properties": {
                        "status": {
                            "type": "string",
                            "title": "レコーディングの状態",
                            "description": "レコーディングの状態を識別する文字列。",
                            "enum": ["recording", "stop", "pause", "resume", "mutetrack", "unmutetrack", "error", "warning"]
                        },
                        "path": {
                            "type": "string",
                            "title": "ファイルパス",
                            "description": "ファイルが存在するパス。ルートはデバイスプラグインごとに違う。File APIで使用可能。"
                        },
                        "mimeType": {
                            "type": "string",
                            "title": "MIME Type",
                            "description": "録画・録音が開始されたメディアのMIME Type。このタイプで、動画、音声などを識別する。"
                        },
                        "errorMessasge": {
                            "type": "string",
                            "title": "エラーメッセージ",
                            "description": "エラー、警告内容を伝える文字列。状態が error、warning の時のみ付加される。省略可能。"
                        }
                    }
                }
            }
        },
        "RecorderControlResponse": {
            "type": "object",
            "allOf": [
                {
                    "$ref": "#/definitions/CommonResponse"
                }
            ]
        },
        "EventRegistrationResponse": {
            "type": "object",
            "allOf": [
                {
                    "$ref": "#/definitions/CommonResponse"
                }
            ]
        },
        "EventUnregistrationResponse": {
            "type": "object",
            "allOf": [
                {
                    "$ref": "#/definitions/CommonResponse"
                }
            ]
        },
        "CommonResponse": {
            "type": "object",
            "required": [
                "result",
                "product",
                "version"
            ],
            "properties": {
                "result": {
                    "type": "integer",
                    "title": "処理結果",
                    "description": "0: 正常応答<br>0以外: 異常応答"
                },
                "product": {
                    "type": "string",
                    "title": "DeviceConnectシステムの名前",
                    "description": ""
                },
                "version": {
                    "type": "string",
                    "title": "DeviceConnectシステムのバージョン名",
                    "description": ""
                },
                "hmac": {
                    "type": "string",
                    "title": "レスポンスに対する署名",
                    "description": "アプリケーション側から事前にHMACキーを共有されていた場合は必須。"
                }
            }
        },
        "CommonEvent": {
            "type": "object",
            "required": [
                "serviceId",
                "profile",
                "interface",
                "attribute"
            ],
            "properties": {
                "serviceId": {
                    "type": "string",
                    "title": "サービスID",
                    "description": ""
                },
                "profile": {
                    "type": "string",
                    "title": "プロファイル名",
                    "description": ""
                },
                "interface": {
                    "type": "string",
                    "title": "インターフェース名",
                    "description": ""
                },
                "attribute": {
                    "type": "string",
                    "title": "アトリビュート名",
                    "description": ""
                }
            }
        }
    }
}